name: Pull Request Comment

on:  
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      prNumber:
        required: false
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@29423367f079522048aa7c63f671593b0556ffd5
        env:
          MESSAGE: ${{ inputs.message}}
          PR_NUMBER: ${{ inputs.prNumber }}
        with:
          script: |
            $prNumber = process.env.PR_NUMBER
            $prNumber = $prNumber ? $prNumber : context.issue.number

            github.rest.issues.createComment({
              issue_number: $prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })
