  
name: run script on changing detections
on:
  pull_request:
    paths:
       - 'Detection**'
       - 'Solutions/**/Analytic Rules/**'
      
jobs:
  add-comment:
    uses: ./.github/workflows/addComment.yaml
    if: ${{ !github.event.pull_request.head.repo.fork }}
    with:
      message: |
        **Hello how are you I am GitHub bot**
        😀😀
        I see that you changed templates under the detections/analytic rules folder. Did you remember to update the version of the templates you changed?
        If not, and if you want customers to be aware that a new version of this template is available, please update the ``version`` property of the template you changed.
      prNumber: "${{ github.event.pull_request.number }}"
