name: Slash Command Dispatch
env:
    REPO_OWNER: "${{ vars.REPO_OWNER }}"
    REPO_NAME: "${{ vars.REPO_NAME }}"
    GITHUB_TOKEN: "${{ secrets.PAT }}"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [ closed ]

jobs:
  checkAutomatedPR:
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork && github.event.issue.pull_request && (contains(github.event.comment.body, '/package') || contains(github.event.comment.body, '/Package')) }}
    uses: ./.github/workflows/checkAutomatedPR.yaml

  pullRequestStatus:
    needs: checkAutomatedPR
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork && github.event.issue.pull_request && (contains(github.event.comment.body, '/package') || contains(github.event.comment.body, '/Package')) }}
    uses: ./.github/workflows/pullRequestStatus.yaml

  slashCommandDispatch:
    runs-on: ubuntu-latest
    needs: [pullRequestStatus, checkAutomatedPR]
    if: ${{ needs.pullRequestStatus.outputs.isPullRequestMerged == 'False' && needs.checkAutomatedPR.outputs.isAutomatedPR == 'False' && !github.event.pull_request.head.repo.fork}}
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@67dfeb76529b35541a7c536976cba367cd2d364b
        with:
          token: ${{ env.GITHUB_TOKEN }}
          commands: |
            package
            Package
            PACKAGE
          repository: ${{env.REPO_OWNER}}/${{env.REPO_NAME}}
          issue-type: pull-request
          reactions: false

  addAutoPackageLabel:
    name: Add Label of Auto-Package
    needs: slashCommandDispatch
    if: ${{ success() }} 
    uses: ./.github/workflows/addLabelOnPr.yaml
    with:
      labelName: "auto-package"
    secrets: inherit